
'use server';
// Using node-canvas requires a native dependency. In a real server environment,
// you would need to ensure `node-canvas` is installed and its dependencies (Cairo, etc.) are available.
// For this environment, we'll assume it's available.
import { createCanvas } from "canvas";
import { markdownToPlainText } from "./markdown-to-plain-text";

export async function generatePreviewImageFromMarkdown(options: {
  markdown: string;
  width?: number;
  height?: number;
  title?: string;
}): Promise<Buffer> {
  const { markdown, width = 1200, height = 1600, title } = options;

  const text = markdownToPlainText
    ? markdownToPlainText(markdown)
    : markdown.replace(/[#*_`>-]/g, "");

  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  // Background
  ctx.fillStyle = "#F9FAFB";
  ctx.fillRect(0, 0, width, height);

  // Header bar
  ctx.fillStyle = "#2563EB";
  ctx.fillRect(0, 0, width, 80);

  ctx.fillStyle = "#FFFFFF";
  ctx.font = "bold 30px Arial";
  ctx.fillText(title || "Generated Preview", 40, 50);

  // Body text
  ctx.fillStyle = "#111827";
  ctx.font = "16px Arial";

  const maxWidth = width - 80;
  const lineHeight = 26;
  let x = 40;
  let y = 120;

  const words = text.split(/\s+/);
  let line = "";

  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + " ";
    const metrics = ctx.measureText(testLine);
    const testWidth = metrics.width;
    if (testWidth > maxWidth && n > 0) {
      ctx.fillText(line, x, y);
      line = words[n] + " ";
      y += lineHeight;
      if (y > height - 60) {
        ctx.fillText("… (content truncated for preview)", x, y + lineHeight);
        break;
      }
    } else {
      line = testLine;
    }
  }
  if (y <= height - 60) {
    ctx.fillText(line, x, y);
  }

  // Footer brand
  ctx.fillStyle = "#6B7280";
  ctx.font = "12px Arial";
  ctx.fillText(
    "Preview generated by BizSpark – Shah Mubaruk, Your Startup Coach",
    40,
    height - 30
  );

  return canvas.toBuffer("image/png");
}

