
'use client';

import { useState, useTransition, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Document, Packer, Paragraph, HeadingLevel } from "docx";
import { useToast } from "@/hooks/use-toast";
import { generateBusinessPlanAction } from '@/app/tools/business-plan/actions';
import { cn } from '@/lib/utils';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter
} from '@/components/ui/card';
import { Loader2, Download, Printer } from 'lucide-react';
import { Input } from '../ui/input';
import { useFirebase, useDoc, useMemoFirebase } from '@/firebase';
import { doc } from 'firebase/firestore';
import { saveAs } from 'file-saver';
import ReactMarkdown from 'react-markdown';
import { LockedPreview } from '@/components/LockedPreview';


const formSchema = z.object({
  businessName: z.string().min(2, 'Business name must be at least 2 characters.'),
  industry: z.string().min(3, 'Please specify your industry.'),
  country: z.string().min(2, 'Country is required.'),
  city: z.string().optional(),
  businessType: z.string().optional(),
  targetCustomer: z.string().min(10, 'Please describe your target audience.'),
  problem: z.string().min(10, 'Please describe the problem you are solving.'),
  solution: z.string().min(10, 'Please describe your solution.'),
  revenueModel: z.string().min(3, 'Please describe your revenue model.'),
  fundingNeed: z.string().optional(),
  founderBackground: z.string().optional(),
  planDepth: z.enum(['quick', 'investor']),
});

type FormData = z.infer<typeof formSchema>;
type UserPlan = 'free' | 'pro' | 'premium';

async function downloadBusinessPlanDocx(planText: string, businessName: string) {
    // A simple parser to convert markdown to docx paragraphs
    const paragraphs = planText.split('\n').map(line => {
      if (line.startsWith('## ')) {
        return new Paragraph({
          text: line.substring(3),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 },
        });
      }
      if (line.startsWith('# ')) {
          return new Paragraph({
              text: line.substring(2),
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 300, after: 150 },
          });
      }
      if (line.trim().startsWith('- ')) {
        return new Paragraph({
          text: line.trim().substring(2),
          bullet: { level: 0 },
        });
      }
      return new Paragraph(line);
    });

    const doc = new Document({
      sections: [{
        children: [
            new Paragraph({ text: businessName, heading: HeadingLevel.TITLE }),
            new Paragraph({ text: "Generated by Shah Mubaruk's AI Startup Coach", style: "IntenseQuote" }),
            ...paragraphs
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${businessName.replace(/ /g, '_') || "business-plan"}.docx`);
  }

export function BusinessPlanForm() {
  const { user, isUserLoading, firestore } = useFirebase();
  const { toast } = useToast();
  const [isPending, startTransition] = useTransition();
  const [result, setResult] = useState<{ planText: string } | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  const userDocRef = useMemoFirebase(() => {
    if (!user || !firestore) return null;
    return doc(firestore, 'users', user.uid);
  }, [user, firestore]);
  const { data: userData } = useDoc(userDocRef);
  const plan = (userData?.plan as UserPlan) || 'free';


  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      businessName: '',
      industry: '',
      country: 'Bangladesh',
      city: '',
      businessType: '',
      targetCustomer: '',
      problem: '',
      solution: '',
      revenueModel: '',
      fundingNeed: '',
      founderBackground: '',
      planDepth: 'investor',
    },
  });

  useEffect(() => {
    const block = (e: Event) => e.preventDefault();
  
    const preview = document.getElementById("preview-area");
    if (!preview) return;
  
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.ctrlKey && (e.key === "c" || e.key === "a" || e.key === "x")) {
        e.preventDefault();
      }
    };
  
    preview.addEventListener("copy", block);
    preview.addEventListener("cut", block);
    preview.addEventListener("contextmenu", block);
    preview.addEventListener("keydown", handleKeyDown);
  
    return () => {
      preview.removeEventListener("copy", block);
      preview.removeEventListener("cut", block);
      preview.removeEventListener("contextmenu", block);
      preview.removeEventListener("keydown", handleKeyDown);
    };
  }, [result]);

  const onSubmit = (data: FormData) => {
    setError(null);
    setResult(null);

    startTransition(async () => {
      try {
        const formData = new FormData();
        Object.entries(data).forEach(([key, value]) => {
            if (value) {
                formData.append(key, value);
            }
        });
        const aiResult = await generateBusinessPlanAction(formData);
        setResult(aiResult);
      } catch (e) {
        console.error(e);
        setError('An unexpected error occurred. Please try again.');
      }
    });
  };

  const handleDownload = () => {
    if (plan === 'free') {
      toast({
        variant: "destructive",
        title: "Upgrade Required",
        description: (
          <div>
            DOCX export is available for Pro & Premium users only.
            <Button variant="link" asChild className="p-0 h-auto ml-2 text-white">
                <Link href="/pricing">Upgrade Now</Link>
            </Button>
          </div>
        ),
      });
      return;
    }
    if (result && form.getValues().businessName) {
      downloadBusinessPlanDocx(result.planText, form.getValues().businessName);
    }
  };


  if (isUserLoading) {
    return <div className="text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-primary" /></div>;
  }

  if (!user) {
    return (
      <Card className="text-center p-8">
        <CardTitle>Please Log In</CardTitle>
        <CardDescription className="mt-2 mb-4">You need to be logged in to generate a business plan.</CardDescription>
        <Button asChild>
          <Link href="/login">Log In</Link>
        </Button>
      </Card>
    );
  }

  const isLocked = plan === 'free';

  return (
    <div className="grid md:grid-cols-2 gap-8">
        <div>
            <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                <Card>
                    <CardHeader>
                      <CardTitle>Your Business Details</CardTitle>
                      <CardDescription>Provide the details for your new business plan.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <FormField control={form.control} name="businessName" render={({ field }) => ( <FormItem><FormLabel>Business Name</FormLabel><FormControl><Input placeholder="e.g., Spark Innovators Ltd." {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="industry" render={({ field }) => ( <FormItem><FormLabel>Industry / Sector</FormLabel><FormControl><Input placeholder="e.g., Tech Education, SaaS, E-commerce" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="country" render={({ field }) => ( <FormItem><FormLabel>Country</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="city" render={({ field }) => ( <FormItem><FormLabel>City (Optional)</FormLabel><FormControl><Input placeholder="e.g., Dhaka" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="businessType" render={({ field }) => ( <FormItem><FormLabel>Business Type (Optional)</FormLabel><FormControl><Input placeholder="e.g., SaaS, E-commerce, Service" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="targetCustomer" render={({ field }) => ( <FormItem><FormLabel>Target Customer</FormLabel><FormControl><Textarea placeholder="e.g., early-stage founders, SMEs, local entrepreneurs" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="problem" render={({ field }) => ( <FormItem><FormLabel>Problem Statement</FormLabel><FormControl><Textarea placeholder="What main problem are you solving?" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="solution" render={({ field }) => ( <FormItem><FormLabel>Solution Overview</FormLabel><FormControl><Textarea placeholder="How are you solving this problem?" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="revenueModel" render={({ field }) => ( <FormItem><FormLabel>Revenue Model</FormLabel><FormControl><Input placeholder="e.g., subscription, commission, B2B service" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="fundingNeed" render={({ field }) => ( <FormItem><FormLabel>Funding Need (Optional)</FormLabel><FormControl><Input placeholder="e.g., $10k for MVP, $50k for seed round" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField control={form.control} name="founderBackground" render={({ field }) => ( <FormItem><FormLabel>Founder Background (Optional)</FormLabel><FormControl><Textarea placeholder="Briefly describe the founder's experience and strengths" {...field} /></FormControl><FormMessage /></FormItem>)} />
                        <FormField
                            control={form.control}
                            name="planDepth"
                            render={({ field }) => (
                                <FormItem>
                                <FormLabel>Plan depth</FormLabel>
                                <select
                                  {...field}
                                  name="planDepth"
                                  className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring"
                                >
                                  <option value="quick">Quick summary</option>
                                  <option value="investor">Investor-ready (full plan)</option>
                                </select>
                                <p className="text-xs text-muted-foreground">
                                  Quick summary = ছোট overview. Investor-ready = লম্বা, full investor plan.
                                </p>
                                <FormMessage />
                                </FormItem>
                            )}
                        />
                    </CardContent>
                    <CardFooter>
                        <Button type="submit" disabled={isPending} size="lg" className="w-full md:w-auto ml-auto">
                            {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                            Generate Business Plan
                        </Button>
                    </CardFooter>
                </Card>
                </form>
            </Form>
        </div>
        <div id="preview-area">
            {isPending && (
                <Card className="flex flex-col items-center justify-center p-8 h-full">
                    <Loader2 className="h-12 w-12 animate-spin text-primary" />
                    <p className="mt-4 text-muted-foreground">Generating your business plan...</p>
                </Card>
            )}

            {!isPending && !result && (
              <Card className="flex flex-col items-center justify-center p-8 h-full text-center">
                  <CardTitle>Your Plan Awaits</CardTitle>
                  <CardDescription className="mt-2">Fill in the form and click 'Generate Business Plan' to see your plan here.</CardDescription>
              </Card>
            )}
            
            {result && (
              <LockedPreview isLocked={isLocked} title="Generated Business Plan">
                <article className="prose max-w-none dark:prose-invert">
                  <ReactMarkdown>{result.planText}</ReactMarkdown>
                </article>

                {!isLocked && (
                  <CardFooter className="flex-col sm:flex-row gap-2 mt-4 p-0">
                      <div className="w-full">
                          <Button
                              onClick={handleDownload}
                              className="w-full sm:w-auto"
                          >
                              <Download className="mr-2" /> Download as Word (.docx)
                          </Button>
                      </div>
                      <Button onClick={() => window.print()} variant="outline" className='w-full sm:w-auto'>
                          <Printer className="mr-2" /> Print / Save as PDF
                      </Button>
                  </CardFooter>
                )}
              </LockedPreview>
            )}

            {error && (
                <Card className="mt-8 border-destructive bg-destructive/10">
                    <CardHeader>
                        <CardTitle className="text-destructive">An Error Occurred</CardTitle>
                        <CardDescription className="text-destructive/80">{error}</CardDescription>
                    </CardHeader>
                </Card>
            )}
        </div>
    </div>
  );
}
